-- Supabase SQL for the products table used by the catalog
-- Run this in Supabase SQL Editor or via psql

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  category text not null,
  name text not null,
  description text,
  price numeric(10,2) not null default 0,
  tag text,
  tag_color text,
  img text,
  emoji text,
  gradient text,
  has_img boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.products
  enable row level security;

-- Example policy for public read access when using anon/public key
create policy "Allow public select" on public.products
  for select using (true);
