-- Create categories table to store catalog groups
create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  emoji text,
  created_at timestamptz not null default now()
);

-- Optional: allow public select (adjust for your security needs)
alter table public.categories enable row level security;

create policy "Allow select for anon" on public.categories for select using (true);
